# Generated by Django 2.1.1 on 2018-11-18 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('short', models.CharField(max_length=3)),
                ('long', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxid', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Division')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Taxonomy')),
            ],
            options={
                'ordering': ('taxid',),
            },
        ),
    ]
