# Generated by Django 3.0.5 on 2020-05-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Taxonomy')),
            ],
        ),
    ]
