# Generated by Django 3.0.5 on 2020-05-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_accession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='taxonomy',
            field=models.IntegerField(),
        ),
    ]
